{% set data = load_setup_py_data(setup_file="../setup.py",
  from_recipe_dir=True) %}

package:
  name: {{ data.get('name') }}
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python {{ data['python_requires'] }}
    - setuptools

  run:
    - python {{ data['python_requires'] }}
    - imageio
    - numpy
    - py-opencv>=2.4
    - matplotlib

test:
  imports:
    - {{data.get('name')}}

about:
  home: {{ data.get('url')}}
  license: {{ data.get('license')}}
  summary: {{ data.get('description')}}
  author: {{ data.get('author')}}
  description: {{ data.get('long_description')}}
